# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/784a5a28-f4ed-4279-8306-cf05cd2c6f99";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/784a5a28-f4ed-4279-8306-cf05cd2c6f99";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/home/jonathan/projects" =
    { device = "/dev/disk/by-uuid/784a5a28-f4ed-4279-8306-cf05cd2c6f99";
      fsType = "btrfs";
      options = [ "subvol=@home_projects" ];
    };

  fileSystems."/home/jonathan/backup" =
    { device = "/dev/disk/by-uuid/784a5a28-f4ed-4279-8306-cf05cd2c6f99";
      fsType = "btrfs";
      options = [ "subvol=@home_backup" ];
    };

  fileSystems."/home/jonathan/.cache" =
    { device = "/dev/disk/by-uuid/784a5a28-f4ed-4279-8306-cf05cd2c6f99";
      fsType = "btrfs";
      options = [ "subvol=@home_cache" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/784a5a28-f4ed-4279-8306-cf05cd2c6f99";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/media" =
    { device = "/dev/disk/by-uuid/0ee3bd0d-25f4-4e3b-9d0a-96eef5258b11";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A7D-E417";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
